In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from Myhelper import *

In [2]:
from proj1_helpers import *
from implementations import *
np.set_printoptions(precision=3, suppress=True)

In [3]:
labels, features, ids = load_csv_data('train.csv') 

In [4]:
labels = (labels + 1) /2 
labels

array([1., 0., 0., ..., 1., 0., 0.])

In [5]:
print(features)

[[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]]


In [6]:
feature_dict = {"DER_mass_MMC":0,
"DER_mass_transverse_met_lep":1,
"DER_mass_vis":2,
"DER_pt_h":3,
"DER_deltaeta_jet_jet":4,
"DER_mass_jet_jet":5,
"DER_prodeta_jet_jet":6,
"DER_deltar_tau_lep":7,
"DER_pt_tot":8,
"DER_sum_pt":9,
"DER_pt_ratio_lep_tau":10,
"DER_met_phi_centrality":11,
"DER_lep_eta_centrality":12,
"PRI_tau_pt":13,
"PRI_tau_eta":14,
"PRI_tau_phi":15,
"PRI_lep_pt":16,
"PRI_lep_eta":17,
"PRI_lep_phi":18,
"PRI_met":19,
"PRI_met_phi":20,
"PRI_met_sumet":21,
"PRI_jet_num":22,
"PRI_jet_leading_pt":23,
"PRI_jet_leading_eta":24,
"PRI_jet_leading_phi":25,
"PRI_jet_subleading_pt":26,
"PRI_jet_subleading_eta":27,
"PRI_jet_subleading_phi":28,
"PRI_jet_all_pt":29}

In [7]:
feature_0 = features[features[:, feature_dict["PRI_jet_num"]] == 0, :]
feature_1 = features[features[:, feature_dict["PRI_jet_num"]] == 1, :]
feature_2 = features[features[:, feature_dict["PRI_jet_num"]] == 2, :]
feature_3 = features[features[:, feature_dict["PRI_jet_num"]] == 3, :]
label_0 = labels[features[:, feature_dict["PRI_jet_num"]] == 0]
label_1 = labels[features[:, feature_dict["PRI_jet_num"]] == 1]
label_2 = labels[features[:, feature_dict["PRI_jet_num"]] == 2]
label_3 = labels[features[:, feature_dict["PRI_jet_num"]] == 3]

In [8]:
feature_0.shape[0] + feature_1.shape[0] +feature_2.shape[0] +feature_3.shape[0] 

250000

In [9]:
drop_feature_0 = [feature_dict["DER_deltaeta_jet_jet"],
feature_dict["DER_lep_eta_centrality"],
feature_dict["DER_mass_jet_jet"],
feature_dict["DER_prodeta_jet_jet"],
feature_dict["PRI_jet_all_pt"],
feature_dict["PRI_jet_leading_eta"],
feature_dict["PRI_jet_leading_phi"],
feature_dict["PRI_jet_leading_pt"],
feature_dict["PRI_jet_num"],
feature_dict["PRI_jet_subleading_eta"],
feature_dict["PRI_jet_subleading_phi"],
feature_dict["PRI_jet_subleading_pt"],
feature_dict["PRI_lep_phi"],
feature_dict["PRI_met_phi"],
feature_dict["PRI_tau_phi"],
feature_dict["DER_mass_MMC"],
feature_dict["PRI_met_sumet"]]

In [10]:
drop_feature_1 = [feature_dict["DER_deltaeta_jet_jet"],
feature_dict["DER_lep_eta_centrality"],
feature_dict["DER_mass_jet_jet"],
feature_dict["DER_prodeta_jet_jet"],
feature_dict["PRI_jet_leading_phi"],
feature_dict["PRI_jet_num"],
feature_dict["PRI_jet_subleading_eta"],
feature_dict["PRI_jet_subleading_phi"],
feature_dict["PRI_jet_subleading_pt"],
feature_dict["PRI_lep_phi"],
feature_dict["PRI_met_phi"],
feature_dict["PRI_tau_phi"],
feature_dict["PRI_jet_leading_pt"],
feature_dict["PRI_jet_all_pt"],
feature_dict["DER_mass_MMC"],
feature_dict["PRI_met_sumet"]]

In [11]:
drop_feature_2 = [feature_dict["PRI_jet_leading_phi"],
feature_dict["PRI_jet_num"],
feature_dict["PRI_jet_subleading_phi"],
feature_dict["PRI_lep_phi"],
feature_dict["PRI_met_phi"],
feature_dict["PRI_tau_phi"],
feature_dict["PRI_jet_leading_pt"],
feature_dict["PRI_jet_all_pt"],
feature_dict["DER_mass_MMC"],
feature_dict["PRI_met_sumet"]]

In [12]:
drop_feature_3 = [feature_dict["PRI_jet_leading_phi"],
feature_dict["PRI_jet_num"],
feature_dict["PRI_jet_subleading_phi"],
feature_dict["PRI_lep_phi"],
feature_dict["PRI_met_phi"],
feature_dict["PRI_tau_phi"],
feature_dict["PRI_jet_leading_pt"],
feature_dict["PRI_jet_all_pt"],
feature_dict["DER_mass_MMC"],
feature_dict["PRI_met_sumet"]]

In [13]:
feature_0 = np.delete(feature_0, drop_feature_0, axis = 1)
feature_1 = np.delete(feature_1, drop_feature_1, axis = 1)
feature_2 = np.delete(feature_2, drop_feature_2, axis = 1)
feature_3 = np.delete(feature_3, drop_feature_3, axis = 1)

In [14]:
feature_3.shape

(22164, 20)

In [15]:
feature_0 = log_normal(feature_0)
feature_1 = log_normal(feature_1)
feature_2 = log_normal(feature_2)
feature_3 = log_normal(feature_3)


In [16]:
feature_0_poly = PolynomialFeatures(2).fit_transform(feature_0)
feature_1_poly = PolynomialFeatures(2).fit_transform(feature_1)
feature_2_poly = PolynomialFeatures(2).fit_transform(feature_2)
feature_3_poly = PolynomialFeatures(2).fit_transform(feature_3)

In [17]:
feature_0_poly.shape

(99913, 105)

In [18]:
label_0.shape[0]

99913

In [19]:
lamb = 0.001

In [20]:
#3 for 0, 5 for 1, 4 for 2, 4 for 3

In [21]:
k_fold = 4
k_indices_0 = build_k_indices(labels, k_fold = 4)

In [23]:
w0 = ridge_regression_cv(label_0, feature_0_poly, lamb, k_indices_0, k_fold)

IndexError: index 168406 is out of bounds for axis 0 with size 99913

In [ ]:
w0 = ridge_regression(label_0, feature_0_poly, lamb)
w1 = ridge_regression(label_1, feature_1_poly, lamb)
w2 = ridge_regression(label_2, feature_2_poly, lamb)
w3 = ridge_regression(label_3, feature_3_poly, lamb)

In [ ]:
label_test, feature_test, id_test = load_csv_data('test.csv') 

In [ ]:
feature_test

In [ ]:
test_0 = feature_test[feature_test[:, feature_dict["PRI_jet_num"]] == 0, :]
test_1 = feature_test[feature_test[:, feature_dict["PRI_jet_num"]] == 1, :]
test_2 = feature_test[feature_test[:, feature_dict["PRI_jet_num"]] == 2, :]
test_3 = feature_test[feature_test[:, feature_dict["PRI_jet_num"]] == 3, :]

In [ ]:
test_0 = np.delete(test_0, drop_feature_0, axis = 1)
test_1 = np.delete(test_1, drop_feature_1, axis = 1)
test_2 = np.delete(test_2, drop_feature_2, axis = 1)
test_3 = np.delete(test_3, drop_feature_3, axis = 1)

In [ ]:
test_0 = log_normal(test_0)
test_1 = log_normal(test_1)
test_2 = log_normal(test_2)
test_3 = log_normal(test_3)

In [ ]:
test_0_poly = PolynomialFeatures(2).fit_transform(test_0)
test_1_poly = PolynomialFeatures(2).fit_transform(test_1)
test_2_poly = PolynomialFeatures(2).fit_transform(test_2)
test_3_poly = PolynomialFeatures(2).fit_transform(test_3)

In [ ]:
test_label_0 = predict_labels(w0, test_0_poly)
test_label_1 = predict_labels(w1, test_1_poly)
test_label_2 = predict_labels(w2, test_2_poly)
test_label_3 = predict_labels(w3, test_3_poly)

In [ ]:
label_test[np.where(feature_test[:, feature_dict["PRI_jet_num"]] == 0)] = test_label_0
label_test[np.where(feature_test[:, feature_dict["PRI_jet_num"]] == 1)] = test_label_1
label_test[np.where(feature_test[:, feature_dict["PRI_jet_num"]] == 2)] = test_label_2
label_test[np.where(feature_test[:, feature_dict["PRI_jet_num"]] == 3)] = test_label_3

In [ ]:
create_csv_submission(id_test, label_test, 'submission.csv')

In [ ]:
best_labels, no_feature, best_ids = load_csv_data('best.csv')

In [ ]:
np.sum(abs(best_labels - label_test) / 2) / best_labels.shape[0]