In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
from proj1_helpers import *
from implementations import *
np.set_printoptions(precision=3, suppress=True)

In [9]:
labels, features, ids = load_csv_data('train.csv') 

In [10]:
print(features)

[[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]]


250000

(30,)

(250000, 30)

(250000, 29)